from brian2.units import ms, mV, second, Hz
from pypet import cartesian_product

input_dict = {'T1': [1*second],
              'T2': [100000]*second,
              'T3': [4*second],
              'dt': [0.1*ms],
              'NPInp': [50, 75, 100, 250, 500, 1000],
              'NPInp_1n': [10],
              'NPInp_inh' : [10000],
              'NPInp_inh_1n': [10],
              'a_EPoi': [0.005],
              'PInp_rate': [260.]*Hz,
              'PInp_inh_rate': [210.]*Hz,
              'p_ee' : [0.1],
              'PInp_mode': ['pool'], # pool
              'amax' : [10.**25],
              'synEE_rec': [0],
              'stdp_active': [1],
              'strct_active': [1],
              'strct_mode': ['zero'],
              'insert_P': [0.0000165],
              'p_inactivate': [0.005],
              'a_insert': [0.],
              'memtraces_rec' : [1],
              'getraces_rec' : [1],
              'gitraces_rec' : [1],
              'GExc_stat_dt' : [2*ms],
              'GInh_stat_dt' : [2*ms],
              'synee_atraces_rec' : [1],
              'synee_Apretraces_rec': [1],
              'synee_Aposttraces_rec': [1],
              'n_synee_traces_rec': [1000],
              'synee_a_nrecpoints': [25],
              'turnover_rec': [1],
              'spks_rec' : [1],
              'synEE_stat_dt' : [2*ms],
              'scl_active': [1], 
              'eta_scaling': [0.2],
              'amax': [0.200/10],
              'Aplus': [0.0015/10],
              'Aminus': [-0.00075/10*1.2, -0.00075/10*1.1,-0.00075/10, -0.00075/10*0.9, -0.00075/10*0.8],
              #'Aminus': [-0.00075/10],
              'a_ee' : [0.005/10],
              'a_ie' : [0.005/10],
              'a_ei' : [-0.005/10],
              'a_ii'  : [-0.005/10],
              'ATotalMax': [0.200/10],
              'ascale': [1.0]}

name = 'test_poissonian_input'
explore_dict = cartesian_product(input_dict)




# input_dict = {'T': [1026*second],
#               'T1': [1*second],
#               'T2': [1000*second],
#               'T3': [25*second],
#               'dt': [0.1*ms],
#               'sigma_e': [2**0.5]*mV,
#               'sigma_i': [2**0.5]*mV,
#               'p_ee' : [0.15],
#               'amax' : [10.**25],
#               'synEE_rec': [0],
#               'stdp_active': [1],
#               'strct_active': [1],
#               'strct_mode': ['zero'],
#               'insert_P': [0., 0.00000001, 0.0000001,0.000001, 0.00001, 0.0001],
#               'p_inactivate' : [0.005],
#               'a_insert': [0.000],
#               #'prn_thrshld': [0.00049],
#               'memtraces_rec' : [1],
#               'vttraces_rec' : [0],
#               'getraces_rec' : [1],
#               'gitraces_rec' : [1],
#               'GExc_stat_dt' : [2*ms],
#               'GInh_stat_dt' : [2*ms],
#               'synee_atraces_rec' : [1],
#               'synee_Apretraces_rec': [1],
#               'synee_Aposttraces_rec': [1],
#               'n_synee_traces_rec': [1000],
#               'synee_a_nrecpoints': [20],
#               'turnover_rec': [1],
#               'spks_rec' : [0],
#               'synEE_stat_dt' : [2*ms],
#               'scl_active': [0],
#               'eta_scaling': [0.2],
#               'amax': [0.10],
#               'Aplus': [0.0015],
#               'Aminus': [-0.00075*0.9],
#               'a_ee' : [0.0005],
#               'a_ie' : [0.005],
#               'a_ei' : [-0.005],
#               'a_ii'  : [-0.005],
#               'ATotalMax': [0.2],
#               'ascale': [1.0]}

# name = input_dict['strct_mode'][0]+'_noise_var_conservative_norec'
# explore_dict = cartesian_product(input_dict)
